wandb_version: 1

learning rate:
  desc: null
  value: 0.00013594918139956446
num_dense_layers:
  desc: null
  value: 3
num_dense_nodes:
  desc: null
  value: 24
activation:
  desc: null
  value: swish
initialization:
  desc: null
  value: He normal
weight_ic:
  desc: null
  value: 74
weight_bcl:
  desc: null
  value: 66
weight_bcr:
  desc: null
  value: 24
weight_domain:
  desc: null
  value: 43
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688941996.151315
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
