wandb_version: 1

learning rate:
  desc: null
  value: 0.017544935568094402
num_dense_layers:
  desc: null
  value: 3
num_dense_nodes:
  desc: null
  value: 74
activation:
  desc: null
  value: tanh
initialization:
  desc: null
  value: He uniform
weight_ic:
  desc: null
  value: 54
weight_bcl:
  desc: null
  value: 48
weight_bcr:
  desc: null
  value: 48
weight_domain:
  desc: null
  value: 35
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688941855.968981
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
